name = "Satisfiability"
uuid = "160ab843-0bc6-4ba4-9585-b7478b70f443"
authors = ["Emi Soroka <esoroka@stanford.edu>, Mykel Kochenderfer, Sanjay Lall"]
version = "0.1.1"

[compat]
julia = "1"
z3_jll = "4.13"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
z3_jll = "1bc4e1ec-7839-5212-8f2f-0d16b7bd09bc"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"